sudo: false

language: node_js

node_js:
  - "4"
  - "5"
  - "6"

script: npm run cov

after_success: npm install codecov.io && cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js
